switching to babelex raises error in webapp/personal/views.py
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: l'Einstellungen erfolgreich gespeichert.' is not JSON serializable